apiVersion: v1
kind: Pod
metadata:
    name: devwebapp-pod
    labels:
        app: devwebapp-pod
spec:
    containers:
      - name: app
        image: maxtwinslow1/devwebapp-express
        env:
        - name: VAULT_ADDR
          value: http://host.docker.internal:8200
        - name: VAULT_TOKEN
          value: hvs.651hbBQxwntu7WFdBDEQ7DSV
        - name: SECRET_PATH
          value: kv/max
